name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - evgenygurin

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please search existing issues before creating a new one to avoid duplicates.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened instead?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - API Endpoints
        - AI Service
        - Conversation Service
        - NLP Service
        - Integration Service
        - Database
        - Redis/Caching
        - Authentication
        - Configuration
        - Other
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform/Integration
      description: Which platform or integration is affected (if applicable)?
      options:
        - Not applicable
        - Telegram
        - WhatsApp
        - VK
        - Yandex Alice
        - Wildberries
        - Ozon
        - Bitrix24
        - YooKassa
        - Other
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages/Logs
      description: If applicable, add error messages or log output
      placeholder: Paste error messages or relevant log output here...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: You can drag and drop images here...

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: e.g., 3.11.5
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 13.0, Windows 11]
        - FastAPI version: [e.g., 0.104.1]
        - PostgreSQL version: [e.g., 15.0]
        - Redis version: [e.g., 7.0]
        - Docker: [Yes/No and version if applicable]
      value: |
        - OS: 
        - FastAPI version: 
        - PostgreSQL version: 
        - Redis version: 
        - Docker: 
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for similar problems
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have tested this with the latest version
          required: false
        - label: I am willing to submit a pull request to fix this issue
          required: false