name: Code Review от Claude

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  claude-review:
    if: |
      github.repository == 'evgenygurin/easy-flow' && (
        github.event_name == 'pull_request' ||
        (github.event_name == 'issues' && contains(github.event.issue.body, '@claude')) ||
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude'))
      )
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Запуск Code Review от Claude
        id: claude-review
        uses: anthropics/claude-code-action@beta

        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

          use_sticky_comment: true
          
          allowed_tools: "Bash(pip install),Bash(black),Bash(mypy),Bash(flake8),Bash(pytest),Bash(uvicorn main:app --reload),Read,Grep,Glob,Edit,MultiEdit,Write"
          
          direct_prompt: |
            Ты — опытный разработчик, проводящий code review для проекта на Python/FastAPI. 
            Проанализируй этот pull request и дай обратную связь по следующим пунктам:
            
            - Качество кода и соответствие стандартам Python/FastAPI.
            - Потенциальные баги и уязвимости в безопасности.
            - Производительность и возможности для оптимизации.
            - Соответствие архитектуре проекта.
            - Полнота и качество тестов.
            
            Отвечай на русском языке. Будь конструктивным и дружелюбным.
            При необходимости используй `pytest` для запуска тестов.

