name: AI-ассистент Gemini

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

jobs:
  gemini:
    if: |
      github.repository == 'evgenygurin/easy-flow' && (
        github.event_name == 'pull_request' ||
        github.event_name == 'pull_request_review_comment' ||
        (github.event_name == 'issues' && contains(github.event.issue.body, '@gemini')) ||
        (github.event_name == 'issue_comment' && (
          contains(github.event.comment.body, '@gemini') ||
          contains(github.event.comment.body, '@gemini-cli')
        ))
      )
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
      repository-projects: read
    
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Настройка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Проверка ключа Gemini API
        run: |
          if [ -z "${{ secrets.GEMINI_API_KEY }}" ]; then
            echo "❌ Секрет GEMINI_API_KEY не установлен"
            echo "Пожалуйста, добавьте ваш ключ Gemini API в секреты репозитория"
            exit 1
          fi
          echo "✅ Ключ GEMINI_API_KEY настроен"

      - name: Запуск AI-ассистента Gemini
        uses: google-gemini/gemini-cli-action@main
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Диагностика после запуска
        if: always()
        run: |
          echo "Рабочий процесс завершен со статусом: ${{ job.status }}"
          echo "Репозиторий: ${{ github.repository }}"
          echo "Событие: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "issues" ]; then
            echo "Номер issue: ${{ github.event.issue.number }}"
          elif [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "Комментарий в issue: ${{ github.event.issue.number }}"
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Номер PR: ${{ github.event.pull_request.number }}"
          fi