name: 🧐 Обзор Pull Request (Gemini)

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Номер PR для обзора'
        required: true
        type: number

jobs:
  review-pr:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.action == 'opened') ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@gemini-cli /review'))
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      issues: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.issue.number || github.event.inputs.pr_number }}
      cancel-in-progress: true
    steps:
      - name: Генерация токена GitHub App
        id: generate_token
        if: ${{ vars.APP_ID }}
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Клонирование кода PR
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Получение деталей PR
        id: get_pr_details
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token || secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            PR_NUMBER=${{ github.event.inputs.pr_number }}
          elif [ "${{ github.event_name }}" = "issue_comment" ]; then
            PR_NUMBER=${{ github.event.issue.number }}
            ADDITIONAL_INSTRUCTIONS=$(echo "$COMMENT_BODY" | sed 's/.*@gemini-cli \/review//' | xargs)
            echo "additional_instructions=$ADDITIONAL_INSTRUCTIONS" >> "$GITHUB_OUTPUT"
          else
            PR_NUMBER=${{ github.event.pull_request.number }}
          fi
          echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
          PR_DATA=$(gh pr view $PR_NUMBER --json title,body,additions,deletions,changedFiles,baseRefName,headRefName)
          echo "pr_data=$PR_DATA" >> "$GITHUB_OUTPUT"
          CHANGED_FILES=$(gh pr diff $PR_NUMBER --name-only)
          echo "changed_files<<EOF" >> "$GITHUB_OUTPUT"
          echo "$CHANGED_FILES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Запуск обзора PR от Gemini
        uses: google-gemini/gemini-cli-action@main
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          PR_NUMBER: ${{ steps.get_pr_details.outputs.pr_number }}
          PR_DATA: ${{ steps.get_pr_details.outputs.pr_data }}
          CHANGED_FILES: ${{ steps.get_pr_details.outputs.changed_files }}
          ADDITIONAL_INSTRUCTIONS: ${{ steps.get_pr_details.outputs.additional_instructions }}
          REPOSITORY: ${{ github.repository }}
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OTLP_GCP_WIF_PROVIDER: ${{ secrets.OTLP_GCP_WIF_PROVIDER }}
          OTLP_GOOGLE_CLOUD_PROJECT: ${{ secrets.OTLP_GOOGLE_CLOUD_PROJECT }}
          settings_json: |
            {
              "coreTools": [
                "run_shell_command(echo)",
                "run_shell_command(gh pr view)",
                "run_shell_command(gh pr diff)",
                "run_shell_command(gh pr comment)",
                "run_shell_command(cat)",
                "run_shell_command(head)",
                "run_shell_command(tail)",
                "run_shell_command(grep)",
                "write_file"
              ],
              "telemetry": {
                "enabled": true,
                "target": "gcp"
              },
              "sandbox": false
            }
          prompt: |
            Ты — эксперт по code review. У тебя есть доступ к shell-командам для сбора информации о PR и проведения обзора.
            
            ВАЖНО: Используй доступные shell-команды для сбора информации. Не запрашивай информацию у пользователя.
            
            Начни с выполнения этих команд, чтобы собрать необходимые данные:
            1. Выполни: `echo "$PR_DATA"`, чтобы получить детали PR (в формате JSON)
            2. Выполни: `echo "$CHANGED_FILES"`, чтобы получить список измененных файлов
            3. Выполни: `echo "$PR_NUMBER"`, чтобы получить номер PR
            4. Выполни: `echo "$ADDITIONAL_INSTRUCTIONS"`, чтобы увидеть любые конкретные инструкции по обзору от пользователя
            5. Выполни: `gh pr diff $PR_NUMBER`, чтобы увидеть полный дифф
            6. Для конкретных файлов используй: `cat filename`, `head -50 filename` или `tail -50 filename`
            
            Дополнительные инструкции по обзору:
            Если `ADDITIONAL_INSTRUCTIONS` содержит текст, удели первоочередное внимание этим областям в своем обзоре.
            Примеры инструкций: "проверь безопасность", "оцени производительность", "проверь обработку ошибок", "найди критические изменения"
            
            Когда у тебя будет вся информация, проведи всесторонний code review:
            1. Запиши свой обзор в файл: `write_file("review.md", "<здесь твой подробный отзыв>")`
            2. Опубликуй обзор: `gh pr comment $PR_NUMBER --body-file review.md --repo $REPOSITORY`
            
            Области для обзора:
            - **Безопасность**: Аутентификация, авторизация, валидация ввода, очистка данных
            - **Производительность**: Алгоритмы, запросы к базе данных, кэширование, использование ресурсов
            - **Надежность**: Обработка ошибок, логирование, покрытие тестами, пограничные случаи
            - **Поддерживаемость**: Структура кода, документация, соглашения об именовании
            - **Функциональность**: Корректность логики, выполнение требований
            
            Формат вывода:
            Структурируй свой обзор, используя именно этот формат с markdown:
            
            ## 📋 Краткий итог обзора
            Предоставь краткий обзор PR и общую оценку в 2-3 предложениях.
            
            ## 🔍 Общие замечания
            - Перечисли общие наблюдения о качестве кода
            - Упомяни общие паттерны или архитектурные решения
            - Выдели положительные стороны реализации
            - Отметь повторяющиеся темы в разных файлах
            
            ## 🎯 Конкретные замечания
            Включай разделы ниже, только если в них есть реальные замечания. Если в какой-либо категории приоритета нет проблем, опусти весь этот раздел.
            
            ### 🔴 Критические
            (Включай этот раздел, только если есть критические проблемы)
            Проблемы, которые необходимо устранить перед слиянием (уязвимости безопасности, критические изменения, серьезные баги):
            - **Файл: `имя_файла:строка`** - Описание критической проблемы с конкретной рекомендацией
            
            ### 🟡 Высокий приоритет
            (Включай этот раздел, только если есть проблемы с высоким приоритетом)
            Важные проблемы, которые следует устранить (проблемы с производительностью, недостатки дизайна, значительные баги):
            - **Файл: `имя_файла:строка`** - Описание проблемы высокого приоритета с предлагаемым исправлением
            
            ### 🟢 Средний приоритет
            (Включай этот раздел, только если есть проблемы со средним приоритетом)
            Улучшения, которые повысят качество кода (стилистические проблемы, незначительные оптимизации, лучшие практики):
            - **Файл: `имя_файла:строка`** - Описание улучшения среднего приоритета
            
            ### 🔵 Низкий приоритет
            (Включай этот раздел, только если есть предложения)
            Желательные улучшения и предложения (документация, именование, незначительный рефакторинг):
            - **Файл: `имя_файла:строка`** - Описание предложения или улучшения
            
            **Примечание**: Если ни в одной из категорий не найдено конкретных проблем, просто укажи "В ходе этого обзора конкретных проблем не выявлено."
            
            ## ✅ Что понравилось
            (Включай этот раздел, только если есть положительные моменты, которые стоит выделить)
            - Упомяни конкретные удачные практики или реализации
            - Отметь хорошо написанные участки кода
            - Обрати внимание на улучшения по сравнению с предыдущими версиями
