name: 🤖 AI Ассистенты

on:
  issues:
    types: [opened, edited, reopened, assigned]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Номер PR для обработки'
        required: false
        type: number

env:
  STANDARD_TIMEOUT: 15

jobs:
  # Claude AI Assistant
  claude:
    name: Claude Assistant
    if: |
      github.repository == 'evgenygurin/easy-flow' && (
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
        (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
      )
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
      
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Настройка GitHub токена
        id: auth
        uses: ./.github/actions/setup-github-app
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Запуск ассистента Claude
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ steps.auth.outputs.token }}
          allowed_tools: "Bash(pytest),Bash(uvicorn main:app --reload),Bash(pip install -r requirements.txt),Read,Write,Edit,Grep,Glob"
          custom_instructions: |
            Ты работаешь с проектом на Python/FastAPI. Следуй этим правилам:
            - Используй `Black` для форматирования кода.
            - Соблюдай стандарты PEP 8.
            - Добавляй аннотации типов ко всем функциям.
            - Используй `pytest` для тестирования.
            - Отвечай на русском языке.
            - Всегда запускай тесты после внесения изменений в код.

  # Claude Code Review
  claude-review:
    name: Claude Code Review
    if: |
      github.repository == 'evgenygurin/easy-flow' && (
        github.event_name == 'pull_request' ||
        (github.event_name == 'issues' && contains(github.event.issue.body, '@claude-review')) ||
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude-review'))
      )
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Настройка GitHub токена
        id: auth
        uses: ./.github/actions/setup-github-app
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Запуск Code Review от Claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ steps.auth.outputs.token }}
          use_sticky_comment: true
          allowed_tools: "Bash(pip install),Bash(black),Bash(mypy),Bash(flake8),Bash(pytest),Bash(uvicorn main:app --reload),Read,Grep,Glob,Edit,MultiEdit,Write"
          direct_prompt: |
            Ты — опытный разработчик, проводящий code review для проекта на Python/FastAPI. 
            Проанализируй этот pull request и дай обратную связь по следующим пунктам:
            
            - Качество кода и соответствие стандартам Python/FastAPI.
            - Потенциальные баги и уязвимости в безопасности.
            - Производительность и возможности для оптимизации.
            - Соответствие архитектуре проекта.
            - Полнота и качество тестов.
            
            Отвечай на русском языке. Будь конструктивным и дружелюбным.
            При необходимости используй `pytest` для запуска тестов.

  # Gemini AI Assistant
  gemini:
    name: Gemini Assistant
    if: |
      github.repository == 'evgenygurin/easy-flow' && (
        github.event_name == 'pull_request' ||
        github.event_name == 'pull_request_review_comment' ||
        (github.event_name == 'issues' && contains(github.event.issue.body, '@gemini')) ||
        (github.event_name == 'issue_comment' && (
          contains(github.event.comment.body, '@gemini') ||
          contains(github.event.comment.body, '@gemini-cli')
        ))
      )
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
      repository-projects: read
    
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Настройка GitHub токена
        id: auth
        uses: ./.github/actions/setup-github-app
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Настройка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Проверка ключа Gemini API
        run: |
          if [ -z "${{ secrets.GEMINI_API_KEY }}" ]; then
            echo "❌ Секрет GEMINI_API_KEY не установлен"
            echo "Пожалуйста, добавьте ваш ключ Gemini API в секреты репозитория"
            exit 1
          fi
          echo "✅ Ключ GEMINI_API_KEY настроен"

      - name: Запуск AI-ассистента Gemini
        uses: google-gemini/gemini-cli-action@main
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          
      - name: Диагностика после запуска
        if: always()
        run: |
          echo "Рабочий процесс завершен со статусом: ${{ job.status }}"
          echo "Репозиторий: ${{ github.repository }}"
          echo "Событие: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "issues" ]; then
            echo "Номер issue: ${{ github.event.issue.number }}"
          elif [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "Комментарий в issue: ${{ github.event.issue.number }}"
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Номер PR: ${{ github.event.pull_request.number }}"
          fi

  # Gemini CLI для продвинутых команд  
  gemini-cli:
    name: Gemini CLI
    if: |
      (
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@gemini-cli') && !contains(github.event.comment.body, '/review') && !contains(github.event.comment.body, '/triage')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@gemini-cli') && !contains(github.event.comment.body, '/review') && !contains(github.event.comment.body, '/triage')) ||
        (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@gemini-cli') && !contains(github.event.comment.body, '/review') && !contains(github.event.comment.body, '/triage'))) && 
        (
          github.event.comment.author_association == 'OWNER' ||
          github.event.comment.author_association == 'MEMBER' ||
          github.event.comment.author_association == 'COLLABORATOR'
        )
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Получение ветки PR
        id: get_pr_branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            PR_NUMBER=${{ github.event.issue.number }}
            BRANCH=$(gh pr view "$PR_NUMBER" --json headRefName -q .headRefName --repo "$REPOSITORY")
            echo "name=$BRANCH" >> $GITHUB_OUTPUT
          else
            echo "name=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          fi

      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_pr_branch.outputs.name }}
          fetch_depth: 0

      - name: Настройка GitHub токена
        id: auth
        uses: ./.github/actions/setup-github-app
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Получение деталей PR
        id: get_pr
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          GH_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            PR_NUMBER=${{ github.event.issue.number }}
          else
            PR_NUMBER=${{ github.event.pull_request.number }}
          fi
          echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
          PR_DATA=$(gh pr view $PR_NUMBER --json title,body,additions,deletions,changedFiles,baseRefName,headRefName)
          echo "pr_data=$PR_DATA" >> "$GITHUB_OUTPUT"
          CHANGED_FILES=$(gh pr diff $PR_NUMBER --name-only)
          echo "changed_files<<EOF" >> "$GITHUB_OUTPUT"
          echo "$CHANGED_FILES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Подтверждение запроса
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          GH_TOKEN: ${{ steps.auth.outputs.token }}
          PR_NUMBER: ${{ steps.get_pr.outputs.pr_number }}
          REPOSITORY: ${{ github.repository }}
        run: |
          gh pr comment $PR_NUMBER --body "Я получил ваш запрос и уже работаю над ним! 🤖" --repo $REPOSITORY

      - name: Запуск Gemini CLI
        uses: google-gemini/gemini-cli-action@main
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          REPOSITORY: ${{ github.repository }}
          USER_REQUEST: ${{github.event.comment.body}}
          PR_NUMBER: ${{ steps.get_pr.outputs.pr_number }}
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OTLP_GCP_WIF_PROVIDER: ${{ secrets.OTLP_GCP_WIF_PROVIDER }}
          OTLP_GOOGLE_CLOUD_PROJECT: ${{ secrets.OTLP_GOOGLE_CLOUD_PROJECT }}
          settings_json: |
            {
              "coreTools": [
                "run_shell_command(echo)",
                "run_shell_command(gh pr view)",
                "run_shell_command(gh pr diff)",
                "run_shell_command(gh pr comment)",
                "run_shell_command(cat)",
                "run_shell_command(head)",
                "run_shell_command(tail)",
                "run_shell_command(grep)",
                "run_shell_command(git config)",
                "run_shell_command(git status)",
                "run_shell_command(git add)",
                "run_shell_command(git commit)",
                "run_shell_command(git push)",
                "run_shell_command(git diff)",
                "write_file"
              ],
              "telemetry": {
                "enabled": true,
                "target": "gcp"
              },
              "sandbox": false
            }
          prompt: |
            ВАЖНО: Используй доступные shell-команды для сбора информации, если это необходимо. Не запрашивай информацию у пользователя.
            Начни с выполнения этих команд, чтобы собрать необходимые данные:
              1. Выполни: `echo "$USER_REQUEST"`, чтобы получить запрос пользователя
              2. Выполни: `echo "$REPOSITORY"`, чтобы получить имя репозитория
              3. Выполни: `echo "$PR_NUMBER"`, чтобы получить номер PR
              4. Для конкретных файлов используй: `cat имя_файла`, `head -50 имя_файла` или `tail -50 имя_файла`
            Ответь на $USER_REQUEST;
            Когда будешь готов предоставить ответ, выполни следующие шаги:
            1. Если ты внес изменения в файлы, добавь их с помощью 'git add .'. ВАЖНО: не добавляй файл response.md.
            2. Закоммить изменения с описательным сообщением, используя 'git commit -m "твое сообщение коммита"'.
            3. Отправь изменения в ветку с помощью 'git push'.
            4. Запиши свой ответ в файл: write_file("response.md", "<твой ответ здесь>")
            5. Опубликуй ответ: gh pr comment $PR_NUMBER --body-file response.md --repo $REPOSITORY