name: Claude Monitor

on:
  schedule:
    # Run every hour to check for stuck Claude processes
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: write
      contents: read
    
    steps:
      - name: Cancel stale Claude workflows
        uses: actions/github-script@v7
        with:
          script: |
            const { data: workflows } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'claude.yml',
              status: 'in_progress',
              per_page: 100
            });
            
            const staleWorkflows = workflows.workflow_runs.filter(run => {
              const runTime = new Date() - new Date(run.created_at);
              // Cancel if running for more than 45 minutes
              return runTime > 45 * 60 * 1000;
            });
            
            for (const run of staleWorkflows) {
              console.log(`Cancelling stale workflow run: ${run.id}`);
              await github.rest.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
            }
            
            if (staleWorkflows.length === 0) {
              console.log('No stale Claude workflows found');
            } else {
              console.log(`Cancelled ${staleWorkflows.length} stale Claude workflows`);
            }

      - name: Cancel stale Claude review workflows
        uses: actions/github-script@v7
        with:
          script: |
            const { data: workflows } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'claude-code-review.yml',
              status: 'in_progress',
              per_page: 100
            });
            
            const staleWorkflows = workflows.workflow_runs.filter(run => {
              const runTime = new Date() - new Date(run.created_at);
              // Cancel if running for more than 30 minutes
              return runTime > 30 * 60 * 1000;
            });
            
            for (const run of staleWorkflows) {
              console.log(`Cancelling stale review workflow run: ${run.id}`);
              await github.rest.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
            }
            
            if (staleWorkflows.length === 0) {
              console.log('No stale Claude review workflows found');
            } else {
              console.log(`Cancelled ${staleWorkflows.length} stale Claude review workflows`);
            }