name: Проверка качества кода

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Установка Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Проверка с Ruff (линтинг)
      run: |
        ruff check . --output-format=github

    - name: Проверка с Ruff (форматирование)
      run: |
        ruff format --check .

    - name: Проверка типов с MyPy
      run: |
        mypy app/ --config-file=pyproject.toml

    - name: Проверка безопасности с Bandit
      run: |
        bandit -r app/ -f json -o bandit-report.json || true
        bandit -r app/ -f txt

    - name: Запуск тестов
      run: |
        pytest tests/ -v --tb=short

    - name: Загрузка отчета безопасности
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-security-report
        path: bandit-report.json