name: 🏷️ Автоматическая сортировка issue с помощью Gemini

on:
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Номер issue для сортировки'
        required: true
        type: number

jobs:
  triage-issue:
    if: >
      github.event_name == 'issues' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' && 
       contains(github.event.comment.body, '@gemini-cli /triage') &&
       (github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'))
    timeout-minutes: 5
    permissions:
      issues: write
      contents: read
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.issue.number || github.event.inputs.issue_number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Генерация токена GitHub App
        id: generate_token
        if: ${{ vars.APP_ID }}
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token || secrets.GITHUB_TOKEN }}

      - name: Установка контекста issue
        id: set_issue_context
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "issue_number=${{ github.event.inputs.issue_number }}" >> $GITHUB_OUTPUT
          else
            echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Получение деталей issue
        id: get_issue_details
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token || secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.set_issue_context.outputs.issue_number }}
        run: |
          ISSUE_JSON=$(gh issue view $ISSUE_NUMBER --json title,body)
          echo "issue_title=$(echo $ISSUE_JSON | jq -r .title)" >> $GITHUB_OUTPUT
          # Using a delimiter to handle multiline body
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "issue_body<<$EOF" >> $GITHUB_OUTPUT
          echo "$(echo $ISSUE_JSON | jq -r .body)" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Запуск сортировки issue с помощью Gemini
        uses: google-gemini/gemini-cli-action@main
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token || secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: ${{ steps.get_issue_details.outputs.issue_title }}
          ISSUE_BODY: ${{ steps.get_issue_details.outputs.issue_body }}
          ISSUE_NUMBER: ${{ steps.set_issue_context.outputs.issue_number }}
          REPOSITORY: ${{ github.repository }}
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OTLP_GCP_WIF_PROVIDER: ${{ secrets.OTLP_GCP_WIF_PROVIDER }}
          OTLP_GOOGLE_CLOUD_PROJECT: ${{ secrets.OTLP_GOOGLE_CLOUD_PROJECT }}
          settings_json: |
            {
              "coreTools": [
                "run_shell_command(gh label list)",
                "run_shell_command(gh issue edit)"
              ],
              "telemetry": {
                "enabled": true,
                "target": "gcp"
              },
              "sandbox": false
            }
          prompt: |
            Ты — ассистент по сортировке issue. Проанализируй текущую задачу в GitHub и примени наиболее подходящие из существующих меток.

            Шаги:
            1. Выполни: `gh label list`, чтобы получить список всех доступных меток.
            2. Изучи заголовок и тело issue, которые предоставлены в переменных окружения.
            3. Выбери наиболее релевантные метки из существующих. Если возможно, установи метки, соответствующие шаблонам `kind/*`, `area/*` и `priority/*`.
            4. Примени выбранные метки к этой issue с помощью команды: `gh issue edit ISSUE_NUMBER --add-label "метка1,метка2"`
            5. Если присутствует метка `status/needs-triage`, удали её с помощью команды: `gh issue edit ISSUE_NUMBER --remove-label "status/needs-triage"`

            Правила:
            - Используй только те метки, которые уже существуют в репозитории.
            - Не добавляй комментарии и не изменяй содержимое issue.
            - Сортируй только текущую issue.
            - Назначь все применимые метки на основе содержимого issue.
