name: 📋 Управление Issues

on:
  schedule:
    - cron: '0 * * * *' # Запускается каждый час
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Номер issue для обработки'
        required: true
        type: number
      action:
        description: 'Действие: triage, backup-response'
        required: true
        type: choice
        options:
          - triage
          - backup-response

env:
  STANDARD_TIMEOUT: 10

jobs:
  # Автоматическая сортировка новых issues
  auto-triage:
    name: Автоматическая сортировка
    if: >
      github.event_name == 'issues' ||
      github.event_name == 'workflow_dispatch' && inputs.action == 'triage' ||
      (github.event_name == 'issue_comment' && 
       contains(github.event.comment.body, '@gemini-cli /triage') &&
       (github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'))
    timeout-minutes: 5
    permissions:
      issues: write
      contents: read
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-triage-${{ github.event.issue.number || inputs.issue_number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка GitHub токена
        id: auth
        uses: ./.github/actions/setup-github-app
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Установка контекста issue
        id: set_issue_context
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "issue_number=${{ inputs.issue_number }}" >> $GITHUB_OUTPUT
          else
            echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Получение деталей issue
        id: get_issue_details
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          ISSUE_NUMBER: ${{ steps.set_issue_context.outputs.issue_number }}
        run: |
          ISSUE_JSON=$(gh issue view $ISSUE_NUMBER --json title,body)
          echo "issue_title=$(echo $ISSUE_JSON | jq -r .title)" >> $GITHUB_OUTPUT
          # Using a delimiter to handle multiline body
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "issue_body<<$EOF" >> $GITHUB_OUTPUT
          echo "$(echo $ISSUE_JSON | jq -r .body)" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Запуск сортировки issue с помощью Gemini
        uses: google-gemini/gemini-cli-action@main
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          ISSUE_TITLE: ${{ steps.get_issue_details.outputs.issue_title }}
          ISSUE_BODY: ${{ steps.get_issue_details.outputs.issue_body }}
          ISSUE_NUMBER: ${{ steps.set_issue_context.outputs.issue_number }}
          REPOSITORY: ${{ github.repository }}
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OTLP_GCP_WIF_PROVIDER: ${{ secrets.OTLP_GCP_WIF_PROVIDER }}
          OTLP_GOOGLE_CLOUD_PROJECT: ${{ secrets.OTLP_GOOGLE_CLOUD_PROJECT }}
          settings_json: |
            {
              "coreTools": [
                "run_shell_command(gh label list)",
                "run_shell_command(gh issue edit)"
              ],
              "telemetry": {
                "enabled": true,
                "target": "gcp"
              },
              "sandbox": false
            }
          prompt: |
            Ты — ассистент по сортировке issue. Проанализируй текущую задачу в GitHub и примени наиболее подходящие из существующих меток.

            Шаги:
            1. Выполни: `gh label list`, чтобы получить список всех доступных меток.
            2. Изучи заголовок и тело issue, которые предоставлены в переменных окружения.
            3. Выбери наиболее релевантные метки из существующих. Если возможно, установи метки, соответствующие шаблонам `kind/*`, `area/*` и `priority/*`.
            4. Примени выбранные метки к этой issue с помощью команды: `gh issue edit ISSUE_NUMBER --add-label "метка1,метка2"`
            5. Если присутствует метка `status/needs-triage`, удали её с помощью команды: `gh issue edit ISSUE_NUMBER --remove-label "status/needs-triage"`

            Правила:
            - Используй только те метки, которые уже существуют в репозитории.
            - Не добавляй комментарии и не изменяй содержимое issue.
            - Сортируй только текущую issue.
            - Назначь все применимые метки на основе содержимого issue.

  # Массовая сортировка issues по расписанию
  scheduled-triage:
    name: Плановая сортировка
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      issues: write
      
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка GitHub токена
        id: auth
        uses: ./.github/actions/setup-github-app
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Поиск неотсортированных issue
        id: find_issues
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          echo "🔍 Поиск issue без меток..."
          NO_LABEL_ISSUES=$(gh issue list --repo ${{ github.repository }} --search "is:open is:issue no:label" --json number,title,body)

          echo "🏷️ Поиск issue, требующих сортировки..."
          NEED_TRIAGE_ISSUES=$(gh issue list --repo ${{ github.repository }} --search "is:open is:issue label:\"status/needs-triage\"" --json number,title,body)

          echo "🔄 Объединение и удаление дубликатов issue..."
          ISSUES=$(echo "$NO_LABEL_ISSUES" "$NEED_TRIAGE_ISSUES" | jq -c -s 'add | unique_by(.number)')

          echo "📝 Установка вывода для GitHub Actions..."
          echo "issues_to_triage=$ISSUES" >> "$GITHUB_OUTPUT"

          echo "✅ Найдено $(echo "$ISSUES" | jq 'length') issue для сортировки! 🎯"

      - name: Запуск массовой сортировки issue с помощью Gemini
        if: steps.find_issues.outputs.issues_to_triage != '[]'
        uses: google-gemini/gemini-cli-action@main
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          ISSUES_TO_TRIAGE: ${{ steps.find_issues.outputs.issues_to_triage }}
          REPOSITORY: ${{ github.repository }}
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OTLP_GCP_WIF_PROVIDER: ${{ secrets.OTLP_GCP_WIF_PROVIDER }}
          OTLP_GOOGLE_CLOUD_PROJECT: ${{ secrets.OTLP_GOOGLE_CLOUD_PROJECT }}
          settings_json: |
            {
              "coreTools": [
                "run_shell_command(echo)",
                "run_shell_command(gh label list)",
                "run_shell_command(gh issue edit)",
                "run_shell_command(gh issue list)"
              ],
              "telemetry": {
                "enabled": true,
                "target": "gcp"
              },
              "sandbox": false
            }
          prompt: |
            Ты — ассистент по сортировке issue. Анализируй задачи и применяй соответствующие метки.
            
            Шаги:
            1. Выполни: `gh label list`
            2. Проверь переменную окружения: $ISSUES_TO_TRIAGE (JSON-массив с задачами)
            3. Для каждой issue примени метки: `gh issue edit ISSUE_NUMBER --add-label "метка1,метка2"`. Если возможно, установи метки, соответствующие шаблонам `kind/*`, `area/*` и `priority/*`.
            4. Для каждой issue, если присутствует метка `status/needs-triage`, удали её с помощью команды: `gh issue edit ISSUE_NUMBER --remove-label "status/needs-triage"`
            
            Правила:
            - Используй только существующие в репозитории метки.
            - Не добавляй комментарии.
            - Сортируй каждую issue независимо.

  # Резервный ответ Gemini для issues
  gemini-backup:
    name: Резервный ответ Gemini
    if: github.event_name == 'workflow_dispatch' && inputs.action == 'backup-response'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      contents: read
      issues: write
      pull-requests: write
    
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка GitHub токена
        id: auth
        uses: ./.github/actions/setup-github-app
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Установка зависимостей
        run: |
          pip install requests google-generativeai

      - name: Генерация ответа Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          ISSUE_NUMBER: ${{ inputs.issue_number }}
        run: |
          python3 << 'EOF'
          import os
          import requests
          import google.generativeai as genai
          import json

          # Настройка Gemini
          genai.configure(api_key=os.environ['GEMINI_API_KEY'])
          model = genai.GenerativeModel('gemini-2.5-pro')

          # Получение деталей issue
          repo = os.environ['GITHUB_REPOSITORY']
          issue_number = os.environ['ISSUE_NUMBER']
          
          # Запрос к GitHub API
          headers = {
              'Authorization': f"Bearer {os.environ['GITHUB_TOKEN']}",
              'Accept': 'application/vnd.github+json'
          }
          
          issue_url = f"https://api.github.com/repos/{repo}/issues/{issue_number}"
          response = requests.get(issue_url, headers=headers)
          
          if response.status_code != 200:
              print(f"Ошибка получения issue: {response.status_code}")
              exit(1)
          
          issue_data = response.json()
          
          # Подготовка контекста
          context = f"""
          Ты — AI-ассистент для разработчиков в репозитории {repo}.
          Твоя задача — помочь с issue #{issue_number}.

          **Название:** {issue_data['title']}

          **Описание:**
          {issue_data['body']}

          **Инструкции:**
          1.  **Проанализируй** проблему, описанную в issue.
          2.  **Предложи** решение или следующий шаг.
          3.  Если нужно, **приведи примеры кода**.
          4.  **Отвечай на русском языке.**
          """
          
          try:
              # Генерация ответа
              ai_response = model.generate_content(context)
              response_text = ai_response.text
              
              # Публикация комментария
              comment_data = {
                  'body': f"🤖 **AI-ассистент Gemini (Резервный)**\n\n{response_text}\n\n---\n*Работает на Google Gemini 2.5 Pro*"
              }
              
              comment_url = f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments"
              post_response = requests.post(comment_url, headers=headers, json=comment_data)
              
              if post_response.status_code == 201:
                  print("✅ Ответ AI успешно опубликован в issue")
              else:
                  print(f"❌ Ошибка публикации комментария: {post_response.status_code}")
                  print(post_response.text)
                  
          except Exception as e:
              print(f"❌ Ошибка генерации ответа AI: {str(e)}")
              exit(1)
          EOF